sudo: false
dist: trusty
language: java
jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "skjolber-github"
    token:
      secure: "nObTUg5WO2yrmnonWyhZvpXUrNDOJmy153JaWPcl8D2XKMjmKZExD6UXQDNiwwjGyklB+d2HkyQyBChLre9481nmUf59zTyJ4+Wgzh6nmV4mVmGMBbxC1MdgaAl63rNPG1oT3hvkaskkGjhPqIPp6XXWArFfVc+DV85ALGWVrlsbVfQjly2+b2B/UaXqJRsdTVQyHxEMkZi0qGkTuTIXqaZh8AK2SZjieG6jtDVhZS7SDR9urUUiBs6/i6WpoS3A2KHTInZQ2OecXDyFTbqiZrPiyfXL35gNJ4p/L3re0RWAfW1JiRJUbjiGOvtUEQ3do5dITY/hdCOIaaF0cODdUD8A0JWcUJHZd00UI1v8VYog3JBJnc9kLnrH3Res/P7s0R4tjfXsoeMOKw+gE9K3AeByyT1chtaoWrZEQ5lzjfDDbZ7iB2GX8bHRvUSALLDqoUA/UMdqAb4QGPemUR/LQ4NGuTzc3wjwMkSlgc4A5QedR3Jg3WuzHyiL8sXD0FSvltDeA5Sg4okhuH9LZNuxaTCPMObvt1pg+isiYcCbhrNmgtuZE/fN4KxkQ8c9A5rVVRIUwGxkviARHntdrilXddZgYfQp5BAMjhWN5AU4t9wHDuA94Qj4iMtHpsDOE1S2yY48qK0HQZc9L7fy5ATyvIstbgs3FSKYxnljNC7XFfU="

before_script:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=256m'" > ~/.mavenrc

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean compile 
  - mvn -P '!jmh' clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
  - mvn -P '!jmh' sonar:sonar -Dsonar.projectKey=skjolber_json-log-filter -Dsonar.coverage.jacoco.xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',')

