# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]    
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: maven
    - name: Test
      run: mvn clean test
    - name: Verify
      run: mvn verify -DskipTests
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.5.1
      with:
          token: ${{ secrets.CODECOV_TOKEN }}      
          
